src/pypi_attestation_models/_impl.py
test/test_impl.py

This avoids the need to buffer the entire input in memory.
Closes #13.

impl: stream into sha256

---

src/pypi_attestation_models/_impl.py
test/test_impl.py

This tweaks the `verify` API to return the in-toto predicate type and payload, which might be `None` if no payload is explicitly encoded. 
Also updates the tests to assert those return values.

verify: return statement bits

---

README.md
src/pypi_attestation_models/__init__.py
src/pypi_attestation_models/_impl.py
test/test_impl.py

Move free functions to Attestation

---

.git-blame-ignore-revs
Makefile
README.md
pyproject.toml
src/pypi_attestation_models/__main__.py
src/pypi_attestations/__init__.py
src/pypi_attestations/__main__.py
src/pypi_attestations/_cli.py
src/pypi_attestations/_impl.py
test/test_cli.py
test/test_impl.py
test/test_init.py

Rename to pypi-attestations

---

CHANGELOG.md
src/pypi_attestations/_impl.py
test/test_impl.py

Prevent third party exceptions to leak from `Attestation.sign`.

---

src/pypi_attestations/_impl.py
test/test_impl.py

This ratchets verification down slightly: we reject the payload even if signed if it doesn't match one of our known attestation types, rather than expecting the caller to check the attestation type.
The caller can still further filter verification, e.g. by rejecting attestation types known to `pypi-attestations` but not supported by the caller.
WIP; needs tests.

Add `AttestationType`, check during verify

---

CHANGELOG.md
src/pypi_attestations/_cli.py
src/pypi_attestations/_impl.py
test/test_impl.py

src, test: remove I/O from sign/verify APIs

---

.github/workflows/tests.yml
CHANGELOG.md
pyproject.toml

Upgrade the minimum Python version to `3.11`.
Of note, `warehouse` is on [3.12](https://github.com/pypi/warehouse/blob/main/.python-version) so we could safely also require `3.12`. WDYT?

Upgrade minimum Python version

---

pyproject.toml
test/test_impl.py

* Uses the default build backend
* Renames TestModel -> DummyModel (fixes pytest confusion)
* Bumps sigstore to ~3.3

misc cleanup

---

.github/workflows/release.yml

This better separates our concerns (i.e. dist building vs. publishing).

release: split jobs, refactor

---

README.md

This cleans up the README in a few important ways:
* Moves the CLI docs below the API docs, and emphasizes that they're for experimentation and not integration.
* Adds annotations/callouts throughout where appropriate.
* Updates the library usage examples.
See #55.

README: reorganize, add callouts

---

.github/workflows/tests.yml
CHANGELOG.md
src/pypi_attestations/_cli.py
test/test_cli.py

_cli: exit with an error code when verification fails

---

src/pypi_attestations/_cli.py

Just a small tweak to the `inspect` output, making it hopefully more clear that the certificate's subjects (i.e. SANs) are suitable `--identity` values.
See #55.

_cli: make it clear that subjects are identities

---

.github/workflows/tests.yml
CHANGELOG.md
pyproject.toml
src/pypi_attestations/__init__.py
src/pypi_attestations/_impl.py
test/test_impl.py

Also prepare for 0.0.13 release

Make minimum Python version 3.9 again

---

CHANGELOG.md
src/pypi_attestations/_impl.py
test/test_impl.py

These should be treated like tarball sdists,
but were rejected incorrectly.
Preps a new release in the process.
See: https://github.com/pypa/gh-action-pypi-publish/pull/295#issuecomment-2460919798

fix handling of zip sdists

---

.github/workflows/release.yml
CHANGELOG.md
src/pypi_attestations/__init__.py
src/pypi_attestations/_impl.py
test/test_impl.py

This PR:
- Removes the `claims` field from the Publishers, since it's no longer used
- Adds a step to the release GHA workflow to generate GH provenances
- Bumps the version to `0.0.17` and updates the changelog

Mix fixes and prep release for `0.0.17`

---

pyproject.toml
src/pypi_attestations/_impl.py
test/test_impl.py

Now that `pydantic` 2.10.0 was released with the fix for https://github.com/pydantic/pydantic/issues/9072, this PR removes the workaround implemented in https://github.com/trailofbits/pypi-attestations/pull/48.
Relevant entry in the release notes: https://pydantic.dev/articles/pydantic-v2-10-release#use-b64decode-and-b64encode-for-base64bytes-and-base64str-types

Bump pydantic to 2.10.0 and remove Base64 workaround

---

CHANGELOG.md
src/pypi_attestations/__init__.py

Preps a release that supports sigstore-python 3.6.0.
Signed-off-by: William Woodruff <william@trailofbits.com>

chore: prep 0.0.20

---

README.md
pyproject.toml
src/pypi_attestations/_cli.py
test/test_cli.py

The `verify` CLI subcommand is now split into two:
- `verify attestation`, which behaves as the previous `verify` command (verifies an artifact and its corresponding PEP740 attestation)
- `verify pypi`, which takes the URL of a distribution hosted on PyPI and a signing identity and verifies them.
Examples:
```sh
$ pypi-attestations verify pypi https://files.pythonhosted.org/packages/f0/d5/1341f23a51e45b7780ed6e0b1df3efc9ec4350a528b3f15ec83146edd6ab/abi3info-2025.1.9-py3-none-any.whl --repository https://gitlab.com/woodruffw/abi3info
Verification failed: provenance was signed by a github.com repository, but expected a gitlab.com repository
$ pypi-attestations verify pypi https://files.pythonhosted.org/packages/f0/d5/1341f23a51e45b7780ed6e0b1df3efc9ec4350a528b3f15ec83146edd6ab/abi3info-2025. …
```

Add `pypi-attestations verify pypi` CLI subcommand

---

CHANGELOG.md
README.md
src/pypi_attestations/_cli.py
test/test_cli.py

Rather than specify the full `pythonhosted.org` url for artifacts, now `verify pypi` also supports the friendlier syntax `$PKG_NAME/$FILE_NAME`
```
pypi-attestations verify pypi --repository https://github.com/sigstore/sigstore-python \
sigstore/sigstore-3.6.1-py3-none-any.whl
```
This fixes https://github.com/trailofbits/pypi-attestations/issues/84

cli: Support friendlier syntax for `verify pypi` command

---

.github/workflows/docs.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/tests.yml
src/pypi_attestations/_cli.py
test/test_cli.py
test/test_impl.py

Explicitly specify `encoding` and run tests with `-X warn_default_encoding` / `PYTHONWARNDEFAULTENCODING` set. In most cases we just replace `read_text` with `read_bytes` as `model_validate_json()` can take `bytes`.
A

Fix encoding warnings

---

CHANGELOG.md
src/pypi_attestations/_cli.py
test/test_cli.py

Fixes some CI failures + updates the tests to reflect the new `inspect` behavior (non-matching filenames are now ignored rather than treated as failures).

_cli: `make reformat`

---

pyproject.toml

Add the missing `build-system` section to fix compatibility with strict PEP 517 installers.  Per PEP 517, projects are required to either specify a backend explicitly *or* (for compatibility with legacy projects) provide a `setup.py` file.

build: Add the missing `build-system` section to fix building
